logging:
  receivers:
    webapp_log:
      type: files
      include_paths:
        - /var/log/csye6225/*.log
      record_log_file_path: true
  processors:
    webapp_severity:
      type: parse_severity
      fields:
        severity:
          move_from: jsonPayload.level
    webapp_json:
      type: parse_json
      time_key: timestamp
      time_format: "%Y-%m-%dT%H:%M:%S.%LZ"
  service:
    pipelines:
      webapp_pipeline:
        receivers:
          - webapp_log
        processors:
          - webapp_severity
          - webapp_json