name: Application Integration Test

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm test
        env:
          PORT: ${{secrets.PORT}}
          HOST: ${{secrets.HOST}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_DIALECT: ${{secrets.DB_DIALECT}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
