name: Github Actions Test

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    name: github-actions-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      # - name: Run fail tests
      #   run: npm run fail-test

      - name: Run pass tests
        run: npm run pass-test
