name: MySQL Integration Test

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  integration-tests:
    name: MySQL Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install MySQL
        run: |
          sudo apt-get update
          mysql --version

      - name: Create MySQL Database
        run: |
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS mydb;" -u root -p root

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm test
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
