name: MySQL Integration Test

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  integration-tests:
    name: MySQL Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install MySQL
        run: |
          sudo apt-get update
          mysql --version
          sudo service mysql start

      - name: Create Database, User and Grant Permission for MySQL
        run: |
          sudo mysql --user=${{ secrets.DB_ROOT_USER }} --password=${{ secrets.DB_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
          sudo mysql --user=${{ secrets.DB_ROOT_USER }} --password=${{ secrets.DB_ROOT_PASSWORD }} -e "show databases;"

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm test
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_USER: ${{ secrets.DB_ROOT_USER }}
          DB_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
