name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Update and Verify MySQL
        run: |
          sudo apt-get update
          mysql --version

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Create a database
        run: sudo mysql -u ${{secrets.DB_USER}} --password=${{secrets.DB_PASSWORD}} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"

      - name: Install dependencies
        run: npm install

      - name: give permission to create log file
        run: |
          sudo mkdir -p /var/log/csye6225
          sudo touch /var/log/csye6225/webapp.log
          sudo chmod 640 /var/log/csye6225/*.log

      - name: Run integration tests
        run: npm test
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
