name: Packer Image Builder for GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1
        with:
          version: 1.7.3

      - name: Set up GCP Service Account
        uses: google-github-actions/auth@v2
        id: auth
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: gcloud CLI
        run: gcloud info

      - name: Zip Project
        run: zip -r webapp.zip .

      - name: Verify Zip
        run: ls -l

      - name: Build Packer Image
        run: packer build ./packer/.
