name: Packer Image Builder for GCP

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 1.7.3

      - name: Set up GCP Service Account
        uses: google-github-actions/auth@v2
        id: auth
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: gcloud CLI
        run: gcloud info

      - name: Zip Project
        run: zip -r webapp.zip .

      - name: Verify Zip
        run: ls -l

      - name: Packer init
        run: packer init ./packer/.

      - name: Format Packer template
        run: packer fmt -check ./packer/.

      - name: Verify scripts
        run: ls -l ./packer/scripts

      - name: Validate Packer template
        run: packer validate -var 'project_id=${{secrets.PROJECT_ID}}' -var 'zone=${{secrets.ZONE}}' ./packer/.

      - name: Build Packer Image
        run: packer build -var 'project_id=${{secrets.PROJECT_ID}}' -var 'zone=${{secrets.ZONE}}' ./packer/. | tee build.log

      - name: Extract Image Name
        run: |
          IMAGE_NAME=$(grep -oP 'A disk image was created in the .+ project: \K.+' build.log)
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Authenticate with gcloud CLI
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json

      - name: Generate a unique template name
        id: vars
        run: echo "TEMPLATE_NAME=${{ secrets.TEMPLATE_NAME }}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Retrieve database password and host secrets
        run: |
          echo "DB_PASSWORD=$(gcloud secrets versions access latest --secret=db_password)" >> $GITHUB_ENV
          echo "DB_HOST=$(gcloud secrets versions access latest --secret=db_host)" >> $GITHUB_ENV
          echo "KEY_RING=$(gcloud secrets versions access latest --secret=key_ring)" >> $GITHUB_ENV

      - name: Create a new instance template
        run: |
          gcloud compute instance-templates create ${{ env.TEMPLATE_NAME }} \
            --region=us-east1 \
            --machine-type=${{ secrets.MACHINE_TYPE }} \
            --image=projects/csye6225-cloud-dev-415002/global/images/${{env.IMAGE_NAME}} \
            --boot-disk-type=pd-standard \
            --boot-disk-kms-key=projects/csye6225-cloud-dev-415002/locations/us-east1/keyRings/${{env.KEY_RING}}/cryptoKeys/vm-key \
            --subnet=${{ secrets.SUBNETWORK }} \
            --service-account=${{ secrets.SERVICE_ACCOUNT_EMAIL }} \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --tags=${{ secrets.TAGS }} \
            --metadata=db_host=${{env.DB_HOST}},db_name=webapp,db_password=${{env.DB_PASSWORD}},db_user=webapp,startup-script=\#\!/bin/bash$'\n'$'\n'DB_NAME=\$\(curl\ http://metadata.google.internal/computeMetadata/v1/instance/attributes/db_name\ -H\ \"Metadata-Flavor:\ Google\"\)$'\n'DB_USER=\$\(curl\ http://metadata.google.internal/computeMetadata/v1/instance/attributes/db_user\ -H\ \"Metadata-Flavor:\ Google\"\)$'\n'DB_PASSWORD=\$\(curl\ http://metadata.google.internal/computeMetadata/v1/instance/attributes/db_password\ -H\ \"Metadata-Flavor:\ Google\"\)$'\n'DB_HOST=\$\(curl\ http://metadata.google.internal/computeMetadata/v1/instance/attributes/db_host\ -H\ \"Metadata-Flavor:\ Google\"\)$'\n'$'\n'cat\ \>\ /opt/webapp/.env.development\ \<\<\ EOF$'\n'PORT=8080$'\n'HOST=\"localhost\"$'\n'DB_DIALECT=\"mysql\"$'\n'DB_NAME=\$DB_NAME$'\n'DB_USER=\$DB_USER$'\n'DB_PASSWORD=\$DB_PASSWORD\ $'\n'DB_HOST=\$DB_HOST$'\n'$'\n'GCLOUD_PROJECT_ID=\"csye6225-cloud-dev-415002\"$'\n'$'\n'EMAIL_VERIFICATION_TIMEOUT\ =\ 300000$'\n'EOF$'\n'$'\n'sudo\ systemctl\ start\ webapp.service$'\n'

      - name: Update managed instance group to use new template
        run: |
          gcloud compute instance-groups managed set-instance-template ${{ secrets.INSTANCE_GROUP_NAME }} \
            --template=${{ env.TEMPLATE_NAME }} \
            --region=${{ secrets.REGION }}

      - name: Recreate instances in the managed instance group
        run: |
          gcloud compute instance-groups managed rolling-action start-update ${{ secrets.INSTANCE_GROUP_NAME }} \
            --version template=${{ env.TEMPLATE_NAME }} \
            --region=${{ secrets.REGION }} \
            --type=${{secrets.ROLLING_TYPE}}

      - name: Wait for Refresh
        run: |
          gcloud compute instance-groups managed wait-until ${{secrets.INSTANCE_GROUP_NAME}}  \
            --version-target-reached \
            --region=${{ secrets.REGION }}
